version: '3'
services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      HACKTIV_APP_NAME: Final Assignment
      HACKTIV_DATABASE_STRING: host=db user=indra password=pass1234 dbname=mygram port=5432 sslmode=disable
      HACKTIV_PORT: 8090
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: indra
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: mygram
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./assets/db/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U indra -d mygram'"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: ["postgres", "-c", "listen_addresses=*"]
volumes:
  db:
    driver: local
